# EmporiUm Sales Territory Analysis

Analysis of in-store sales for **Territory manager: Miami Vue (New Jersey)** and **Territory manager: See Ellefson (New York)** 

Dta covers sales transactions, products, and customer rewards data.

In [16]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

### Loading the data

In [17]:
store_detail = pd.read_csv('StoreDetail.csv')
store_sales = pd.read_csv('StoreSales.csv')
products = pd.read_csv('Products.csv')
categories = pd.read_csv('ProductCategories.csv')
customers = pd.read_csv('customer_list.csv')

### Exploring Data

In [18]:
# store detail
store_detail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Store Location     111 non-null    object
 1   State              111 non-null    object
 2   Store ID           111 non-null    int64
 3   Territory Manager  111 non-null    object
 4   Region             111 non-null    object
 5   Region Director    111 non-null    object
dtypes: int64(1), object(5)
memory usage: 5.3+ KB

In [19]:
store_detail.head()

  Store Location     State  Store ID Territory Manager Region  Region Director
0         Aurora  Colorado       701          Jim Heck   West  Cassie Chambers
1       Berthoud  Colorado       702          Jim Heck   West  Cassie Chambers
2        Boulder  Colorado       703          Jim Heck   West  Cassie Chambers
3    Castle Rock  Colorado       704          Jim Heck   West  Cassie Chambers
4         Denver  Colorado       705          Jim Heck   West  Cassie Chambers

In [20]:
# store sales
store_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335129 entries, 0 to 335128
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction Date  335129 non-null  object
 1   Store ID          335129 non-null  int64
 2   RewardsID         34943 non-null   float64
 3   Prod Num          335129 non-null  object
 4   Sale Amount       335129 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 12.8+ MB

In [21]:
store_sales.head()

  Transaction Date  Store ID  RewardsID  Prod Num  Sale Amount
0         1/1/2022       702        NaN  105349-M         8.00
1         1/1/2022       704        NaN  105350-T       144.00
2         1/1/2022       705        NaN  105351-M        44.00
3         1/1/2022       705        NaN  105352-M        47.61
4         1/1/2022       705        NaN  105353-A        20.36

In [22]:
# products
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 669 entries, 0 to 668
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Prod Num       669 non-null    object
 1   Product        669 non-null    object
 2   CategoryID     669 non-null    int64
 3   SubcategoryID  669 non-null    object
dtypes: int64(1), object(3)
memory usage: 21.0+ KB

In [23]:
products.head()

    Prod Num                        Product  CategoryID SubcategoryID
0  105248-IT               TCL NXTPAPER 10s         120       120-tab
1  105249-IT  Dell Latitude 7320 Detachable         120       120-tab
2  105250-IT                     Realme Pad         120       120-tab
3  105251-IT             Lenovo Tab P12 Pro         120       120-tab
4  105252-IT        Microsoft Surface Pro 9         120       120-tab

In [24]:
# categories 
categories.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CategoryID     52 non-null     int64
 1   Category       52 non-null     object
 2   SubcategoryID  52 non-null     object
 3   Subcategory    52 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.8+ KB

In [25]:
categories.head()

   CategoryID                  Category SubcategoryID           Subcategory
0         120  Technology & Accessories       120-tab               Tablets
1         120  Technology & Accessories       120-cal           Calculators
2         120  Technology & Accessories       120-sof     Software Download
3         120  Technology & Accessories       120-hea            Headphones
4         120  Technology & Accessories       120-ext  External Accessories

In [26]:
# Customer data
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 521 entries, 0 to 520
Data columns (total 1 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   cust_id|date|time|name|email|phone|sms-opt-out   521 non-null    object
dtypes: object(1)
memory usage: 4.2+ KB

In [27]:
customers.head()

     cust_id|date|time|name|email|phone|sms-opt-out
0  1|2023-03-15|08:45:12|Rachel|rachel@centralper...
1  2|2023-05-22|12:30:45|R. Geller|rossg@centralp...
2  3|2023-07-09|18:15:27|Monica Geller|chefmonica...
3  4|2023-09-01|21:05:33|Chandler Bing|chandlerb@...
4  5|2023-11-18|14:22:10|Joey|howyoudoing@central...